[platformio]
src_dir = code

[env:m5stack-stickc-plus2]
platform = espressif32@6.7.0
board = m5stick-c
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
board_build.partitions = no_ota.csv
#board_build.filesystem = littlefs
build_flags =
    -DBOARD_HAS_PSRAM=0
    #-mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=0
lib_deps =
    m5stack/M5StickCPlus2@~1.0.1
    dfrobot/DFRobot_GP8XXX@~1.0.1
    m5stack/M5Unified@~0.2.7
	https://github.com/pschatzmann/ESP32-A2DP.git
	https://github.com/pschatzmann/arduino-audio-tools.git
	https://github.com/jcarletto27/M5MicPeakRMS.git
	https://github.com/jcarletto27/ESP32-BT-Scanner.git
